### ISSUE TITLE
Peoples Buildings Remove after Restart

### ISSUE THREAD

**Issue by deannreid** [denisio/Dayz-Epoch-Linux-Server#1] opened 2013-12-18 18:10 UTC
Every time someone builds a base gets cars ect. after a restart they all reset but gear stays the same, I noticed that peoples gear is saved to SQL, and that I believe buildings and Cars are saved to the Cache Folder, Is there a way to save vehicle and building locations to SQL along with the gear?? Thanks.

This is more of a question, but could also be seen as a bug,

**Comment by Curtis-VL** [comment] 2013-12-18 18:26
I'm also having this issue, whenever I restart the server all the vehicles respawn in a random location and all players buildings are gone, it's rather annoying.

**Comment by denisio** [comment] 2013-12-18 19:47
Do you update all files from github?

Please do not forget that the production server must run by "restarter.pl"

**Comment by deannreid** [comment] 2013-12-18 19:49
I have not updated the files from 2 days ago, The last Update I downloaded was initial release of 1.0.3.1, I've downloaded the most recent files and I'm now adding the addons now but its still not been tested, is that the reason?

**Comment by denisio** [comment] 2013-12-18 19:52
Last update fix the diag_log limit.

I can verify the installation if you give me the ssh access.

**Comment by deannreid** [comment] 2013-12-18 20:00
Sorry, I don't own the server so I'm not aloud to give out SSH Access, is there a file I could upload that would verify it?

**Comment by denisio** [comment] 2013-12-18 20:17
Just update it:
https://raw.github.com/denisio/Dayz-Epoch-Linux-Server/master/writer.pl
https://github.com/denisio/Dayz-Epoch-Linux-Server/raw/master/%40dayz_epoch_server/addons/dayz_server.pbo

**Comment by deannreid** [comment] 2013-12-18 20:22
Will check it out, Thanks

**Comment by Curtis-VL** [comment] 2013-12-18 20:45
I hear that in the HiveExt.ini there would be this, and I believe the second line of this is our problem:

;Negative values will disable this feature
;0 means that ALL empty placed items will be deleted every server restart
;A positive number is how old (in days) a placed empty item must be, in order for it to be deleted
;CleanupPlacedAfterDays = 6

One problem, I don't think Hive addon is available for Linux. Any solutions?

**Comment by denisio** [comment] 2013-12-18 21:02
ALL completely damaged items will be deleted every server restart (by writer.pl).

**Comment by deannreid** [comment] 2013-12-21 11:44
That's the problem though, unless everything is damaged and I mean everything buildings, cars, safes pretty much the whole map resets people spawn where they left with their gear, but half the time that resets too!

**Comment by deannreid** [comment] 2013-12-21 11:45
How do you disable damage cleanup on restart in the writer.pl file?

**Comment by denisio** [comment] 2013-12-21 23:08
Please, send me "dump.log" on email: denisio.bro@gmail.com

https://github.com/denisio/Dayz-Epoch-Linux-Server/blob/master/writer.pl#L754

**Comment by denisio** [comment] 2013-12-22 06:23
I think that you have corrupted inventory of some object (fixed now).
For example "dump.log":

<pre>
1:04:12 "HIVE: Starting"
1:04:12 "HIVE: Local Time set to [2012,6,6,1,3]"
1:04:12 "LOAD OBJECTS"
1:04:12 Error in expression R],[1]],[[ItemFuelBarrel,ItemJerrycan,20Rnd_762x51_DMR],[2,4,8]],[[],[]]],[],1.0
1:04:12   Error position: Rnd_762x51_DMR],[2,4,8]],[[],[]]],[],1.0
1:04:12   Error Missing ]
1:04:13 "FOUND  OBJECTS"  - <b>trouble marker! No vehicles will be spawned...</b>
</pre>

You need find and reset it:
1) select ObjectId, Inventory from Object_DATA where Inventory like '%Rnd_762x51_DMR],[2,4,8]],[[],[]]],[],1.0%';
2) update Object_DATA set Inventory='[]' where ObjectId=badobjectid;
3) restarter.pl

**Comment by deannreid** [comment] 2013-12-22 16:29
That is what I was getting, The map seems to have stopped resetting, for the time being, but one or two peoples inventory's got reset, but not others, I'm going to be trying a few more restarts today to see what happens, and I will get back to you!

**Comment by deannreid** [comment] 2013-12-23 03:45
Seems to be working fine now! I think it was due to the account not having enough sql permissions, its currently using the root user just now,   Would you perhaps be able to suggest an auto restarter that includes periodic warnings because the one I found that uses BEC only works on Windows as far as I know

**Comment by denisio** [comment] 2013-12-23 05:00
1) You need to use crontab (for example, restart each 4 hours):
$ echo $HOME
$ crontab -e
0 */4 \* \* \* /home/your_ssh_login/epoch/restarter.pl
2) Check it:
$ crontab -l
3) Edit "restarter.pl":
use constant PATH    => '/home/your_ssh_login/epoch/';

The periodic warning is set by custom debug monitor (show time left until restart):
http://www.youtube.com/watch?v=AOyIqBmtmek
http://8bit.info/dayz/dayz_monitor.png

**Comment by deannreid** [comment] 2013-12-23 16:38
Thanks I'll get this setup today :)

**Comment by deannreid** [comment] 2013-12-26 19:05
Hello, We seem to be having the problem again where the server doesn't read the database everything been working perfect apart from a few inventory's being reset but I've been able to fix those, Our problem only just happened again today where The server doesn't read what is in the "Object_DATA" I'm looking in there and I'm seeing all the items that people have built e.g. Wooden Walls, Cinder walls, their vehicles ect yet the server reads their inventory's fine, I deleted and re-uploaded the Cache folder and it still reads their inventory's, but not anything world side,  I have tried deleting and re-uploading the database, placing a few items and restarting and it reads those fine! but when I re-uploaded the old database nothing appears except inventory's , Do you know what is causing this at all, I'm stumped on the reasoning and cant find a cause to the problem

Here is a pastebin of the Dump.log http://pastebin.com/RVphmuAt

**Comment by deannreid** [comment] 2013-12-26 23:44
Update: I have fixed the fact that buildings wont show up, they do now, but I had to remove every spawned in vehicle on the map, do you know of any limitation of SQL that could mean that it gets too big and stops being able to the database properly? 

Thanks

**Comment by denisio** [comment] 2013-12-29 18:32
You have a lot of script errors in dump.log (z\addons\dayz_server).
Do you modified "@dayz_epoch_server/addons/dayz_server.pbo" ?
Please, use the original file.

**Comment by deannreid** [comment] 2013-12-31 16:30
Yeah, We have custom buildings, and I have DZAI installed,

**Comment by denisio** [comment] 2014-01-05 10:47
Please, use the original file. I don't support any changes.

**Comment by JPPWeber** [comment] 2014-03-03 18:26
You should always start with a vanilla one.
If you have tons of third party scripts, no one can help you in a fast way.
First get a stable server, then make a backup and then start to modify.
Or setup two servers, a live / public one and a passworded dev server.
The second method works like a charm ;)

**Comment by deannreid** [comment] 2014-03-03 18:58
We figured out what was happening, Still waiting for the db to grow since I cleared most unused bases, but hopefully we fixed it :)

**Comment by JPPWeber** [comment] 2014-03-03 19:04
You might tell us, what you have fixed?

**Comment by deannreid** [comment] 2014-03-04 11:30
sorry, we fixed the map wiping on restart, I believe, still waiting a bit to make sure its gone for good.

**Comment by jprice-da15252** [comment] 2014-03-08 17:16
I think you misunderstood  what JPPWeber was asking. What did you find the root cause of the issue to be, and how did you fix that? There are others that may run into the same problem, myself included. Thanks :)

**Comment by deannreid** [comment] 2014-03-09 01:28
Sorry, @denisio found out the problem was one of the rows in the table had the wrong hit-points, which appeared to be the cause 

http://epochmod.com/forum/index.php?/topic/7040-mission-fails-to-read-from-sql-db/?p=53026

**Comment by b-A-shi** [comment] 2014-03-18 13:14
Hey, I have a problem with the Cronjob, I set the correct path to the restarter.pl but I get the error "can't found server binary" any idea for a fix? :)

**Comment by deannreid** [comment] 2014-03-18 13:24
make sure you do    cd / && {LOCATION OF RESTARTER} and that should work

Mine is like this 

cd / && /home/dayzservers/epochpanthera/restarter.pl  just change your dir path and all should work :)

**Comment by b-A-shi** [comment] 2014-03-18 21:49
thank you, i think the cronjob works. i editet the restarter.pl like this "/home/dayz/epoch/" but i get every time the same error message..

**Comment by deannreid** [comment] 2014-03-18 23:31
is that your exact location? also does this happen when you do it manually, also, what user do you run it through?

**Comment by b-A-shi** [comment] 2014-03-19 00:16
If I use the untouched restarter.pl and start it manual it works, if I modify it with the correct path and start manually it's the same error. If I use the untouched cia cron its the same error :(

**Comment by deannreid** [comment] 2014-03-19 17:42
Try making your cron job  cd /home/dayz/epoch && ./restarter.pl

**Comment by deannreid** [comment] 2014-03-19 17:45
sorry remove ,/ and also in the restarter.pl make sure the location is just / and run the cron as root if possible,

**Comment by b-A-shi** [comment] 2014-03-20 01:34
i got it, i set the direct path in the restarer.pl an the cron is this "sudo /home/dayz/epoch/restarter.pl" 
thanks a lot dean!

**Comment by deannreid** [comment] 2014-03-20 17:35
No problem :-)

**Closed as completed** 2014-08-14 21:42 UTC
